services:
  client:
    build: .
    image: ghcr.io/markhuang1212/simple-h2-proxy
    command: yarn run client
    ports: 
      - "9000:9000"
    volumes: 
      - "/etc/h2-proxy:/etc/h2-proxy"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "512M"
  server:
    build: .
    image: ghcr.io/markhuang1212/simple-h2-proxy
    command: yarn run server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/h2-proxy:/etc/h2-proxy"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "512M"
