services:
  client:
    build: .
    ports: 
      - "9000:9000"
    volumes: 
      - "/etc/h2-proxy:/etc/h2-proxy"
  server:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/h2-proxy:/etc/h2-proxy"